name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm run install
      run: npm run install
    - name: npm test
      run: npm test
    - name: npm run compile
      run: npm run compile
